volumes:
  postgres_data:
    driver: local
    name: MemberMGR_Volume

networks:
  default:
    name: ${APP_NETWORK}

services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${APP_NAME}_postgres_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "members_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ${APP_NAME}_api
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_api
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "${API_PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${APP_NAME}_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      postgres:
        condition: service_healthy
