---
# .monitoring/prometheus.yml

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api"
    static_configs:
      - targets: ["api:8000"] # FastAPI container's internal Docker name + port
    metrics_path: /metrics # if using `prometheus-fastapi-instrumentator`

  - job_name: "postgres" # maybe redundent if using `postgres-exporter`
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
