"""add created_at, modified_at and reference_number automatic generation

Revision ID: ba80acc221a9
Revises:
Create Date: 2025-03-06 15:47:51.962634

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision: str = "ba80acc221a9"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Set a default date
default_date = datetime.date.today()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with a default value
    op.add_column(
        "members",
        sa.Column(
            "created_at", sa.Date(), nullable=False, server_default=str(default_date)
        ),
    )
    op.add_column(
        "members",
        sa.Column(
            "modified_at", sa.Date(), nullable=False, server_default=str(default_date)
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("members", "modified_at")
    op.drop_column("members", "created_at")
    # ### end Alembic commands ###
