{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "New Members (last 30 days)",
   "type": "table",
   "description": "Change to Stat box",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)  \nFROM members \nWHERE created_at >= NOW() - INTERVAL '30 days';"
    }
   ]
  },
  {
   "title": "New panel Paid vs Unpaid Memberships (2025)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n   CASE      \n\t   WHEN is_paid \n\t   THEN 'Paid'     \n\t   ELSE 'Unpaid'   \n\tEND AS status,   \n\tCOUNT(*) AS total \nFROM memberships \nWHERE year = 2025 \nGROUP BY status;"
    }
   ]
  },
  {
   "title": "Top 5 Cities by Memberships",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT m.city, COUNT(*) AS members\nFROM members m\nJOIN memberships ms ON m.id = ms.member_id\nGROUP BY m.city\nORDER BY members DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "Member per CIty (2025)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT m.city, COUNT(*) AS total \nFROM members m \nJOIN memberships ms ON m.id = ms.member_id \nWHERE ms.year = 2025\nGROUP BY m.city \nORDER BY total DESC;"
    }
   ]
  },
  {
   "title": " Memberships per Year (modify me)",
   "type": "table",
   "description": "check how to sort by time, order by created at ?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT year, COUNT(*) AS count\nFROM memberships\nGROUP BY year\nORDER BY year;"
    }
   ]
  }
 ]
}