{
 "title": "Container & Host Monitoring (cAdvisor)",
 "description": "Legends have been cleaned.\nTODO: Check data authenticity",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Container CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg without(id, instance, job, interface, container_name) (label_replace(rate(container_cpu_usage_seconds_total{name!=\"\"}[1m]) * 100, \"container\", \"$1\", \"container_label_com_docker_compose_service\", \"(.*)\"))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "megabytes" } },
   "targets": [
    {
     "expr": "avg without(id, instance, job, interface, container_name) (label_replace(container_memory_usage_bytes{name!=\"\"} / 1024 / 1024, \"container\", \"$1\", \"container_label_com_docker_compose_service\", \"(.*)\"))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory Working Set (MB)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "megabytes" } },
   "targets": [
    {
     "expr": "avg without(id, instance, job, interface, container_name) (label_replace(container_memory_working_set_bytes{name!=\"\"} / 1024 / 1024, \"container\", \"$1\", \"container_label_com_docker_compose_service\", \"(.*)\"))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Network Receive (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg without(id, instance, job, interface, container_name) (label_replace(rate(container_network_receive_bytes_total[1m]) / 1024, \"container\", \"$1\", \"container_label_com_docker_compose_service\", \"(.*)\"))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Network Transmit (KB/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg without(id, instance, job, interface, container_name) (label_replace(rate(container_network_transmit_bytes_total[1m]) / 1024, \"container\", \"$1\", \"container_label_com_docker_compose_service\", \"(.*)\"))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container Disk IO (Read + Write MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(\n  avg without(id, instance, job, device) (\n    (\n      rate(container_fs_reads_bytes_total[1m]) +\n      rate(container_fs_writes_bytes_total[1m])\n    ) / 1024 / 1024\n  ),\n  \"container\", \"$1\", \"container_label_com_docker_compose_service\", \"(.*)\"\n)\n",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Filesystem Usage %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "label_replace(\n    avg without(id, instance, job, device) ((container_fs_usage_bytes / container_fs_limit_bytes) * 100),\n      \"container\", \"$1\", \"container_label_com_docker_compose_service\", \"(.*)\"\n)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}