---
# .monitoring/prometheus.yml

global:
  scrape_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/container_alerts.yml"

scrape_configs:
  # Prometheus itself changes slowly, scrape less frequently
  - job_name: "prometheus"
    scrape_interval: 30s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api"
    scrape_interval: 10s
    static_configs:
      - targets: ["api:8000"] # FastAPI container's internal Docker name + port
    metrics_path: /metrics # if using `prometheus-fastapi-instrumentator`

  - job_name: "postgres" # maybe redundent if using `postgres-exporter`
    scrape_interval: 10s
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "cadvisor"
    scrape_interval: 10s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "promtail"
    scrape_interval: 10s
    static_configs:
      - targets: ["promtail:9080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
